language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_deploy:
  - npm run build
deploy:
  cleanup: false
  provider: firebase
  token: "$FIREBASE_TOKEN"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js