language: node_js
node_js:
  - 12
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  app: my-react-burger
  strategy: git
  api_key:
    secure: $HEROKU_API_KEY
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js